version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  seed:
    build: .
    command: npm run seed
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongodb_data: